方框画笔=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(4)

瞄准画笔=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(5)
.setColor(0xffffFFFF)
.setShadowLayer(12,0,0,0xff00FFFF)

人数画笔1=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)


人数画笔2=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setColor(0xffffffff)
.setTextAlign(Paint.Align.CENTER)
.setTextSize(30)
.setFakeBoldText(true)
.setColor(0xffffffff)

射线画笔=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStrokeWidth(3)
.setColor(0xdfffffff)

背敌画笔1=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)

背敌画笔2=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(3)

背敌文字=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setTextSize(30)
.setFakeBoldText(true)
.setTextAlign(Paint.Align.CENTER)

信息画笔=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setColor(0xaf303030)

信息画笔2=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setColor(0xaf303030)

路径方框=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(2)
.setColor(0xffffffff)

距离画笔=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setTextSize(20)
.setFakeBoldText(true)
.setColor(0xffffffff)
.setTextAlign(Paint.Align.RIGHT)

阵营画笔=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setTextSize(23)
.setFakeBoldText(true)
.setColor(0xffffffff)
.setTextAlign(Paint.Align.CENTER)

伤害画笔1=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setTextSize(45)
.setFakeBoldText(true)
.setColor(0xFF00FF00)
.setStrokeWidth(3)
.setTextAlign(Paint.Align.CENTER)

伤害画笔2=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setTextSize(45)
.setFakeBoldText(true)
.setColor(0xFF000000)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(1)
.setTextAlign(Paint.Align.CENTER)

名字画笔=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setTextSize(20)
.setFakeBoldText(true)
.setColor(0xffffffff)
.setTextAlign(Paint.Align.CENTER)

血条画笔1=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(2)
.setColor(0xffffffff)

血条画笔2=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(3)

血条画笔3=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setFakeBoldText(true)
.setTextSize(20)
.setColor(0xffffffff)

准星画笔=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setColor(0xffff0000)

FPS画笔=Paint()
.setAntiAlias(true)--抗锯齿
.setStrokeCap(Cap.ROUND)--圆润边角
.setTextSize(30)--字体大小
.setTextAlign(Paint.Align.CENTER)--字体居中
.setFakeBoldText(true)

圈圈画笔1=Paint()
--.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(2)

圈圈画笔2=Paint()
--.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(3)

圈圈画笔3=Paint()
--.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStyle(Paint.Style.STROKE)
.setStrokeWidth(4)
.setShadowLayer(8,0,0,0xef00FFFF)
.setColor(0xefffffff)

骨骼画笔1=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStrokeWidth(3)
.setColor(0xffffffff)

骨骼画笔2=Paint()
.setAntiAlias(true)
.setStrokeCap(Cap.ROUND)
.setStrokeWidth(3)
.setColor(0xffffffff)
.setStyle(Paint.Style.STROKE)

paint={瞄准画笔,信息画笔2,伤害画笔1,伤害画笔2,FPS画笔,准星画笔,方框画笔,人数画笔1,人数画笔2,射线画笔,背敌画笔1,背敌画笔2,背敌文字,信息画笔,路径方框,距离画笔,阵营画笔,名字画笔,血条画笔1,血条画笔2,血条画笔3}
